const TENANT_CONFIG = {
  TENANT_ID: "{TENANT}",
  APP_NAME: "{APP_NAME}",
  ALLOW_REGISTRATION: {ALLOW_REGISTRATION},
  DEFAULT_ROLE: "{DEFAULT_ROLE}",
  SESSION_TIMEOUT_MINUTES: {SESSION_TIMEOUT},
  ROLES: {ROLES_JSON}
};
